stages:
  - test
  - build

variables:
  CARGO_TERM_COLOR: "always"
  CARGO_INCREMENTAL: "0"

test:
  stage: test
  image: rust:latest
  script:
    - cargo test --workspace --all-targets --all-features
  cache:
    key: "$CI_COMMIT_REF_SLUG-test"
    paths:
      - target/
      - .cargo/

build:
  stage: build
  image: rust:latest
  needs:
    - test
  script:
    - cargo build --workspace --release
    - cargo build -p fish-cli --release
  artifacts:
    paths:
      - target/release/Fish
  cache:
    key: "$CI_COMMIT_REF_SLUG-build"
    paths:
      - target/
      - .cargo/
