[workspace]
resolver = "2"
members = [
    "crates/forge-core",
    "crates/forge-graph",
    "crates/forge-executor",
    "crates/forge-scheduler",
    "crates/forge-cache",
    "crates/forge-backend-rust",
    "crates/forge-backend-cc",
    "crates/forge-backend-go",
    "crates/forge-backend-ts",
    "crates/forge-backend-py",
    "crates/forge-worker",
    "crates/forge-plugin",
    "crates/forge-remote-cache",
    "crates/forge-sandbox",
    "crates/forge-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"
repository = "https://github.com/requla11/forge-rs"
description = "Forge is a fast, flexible, cache-first build orchestration system for Rust and beyond."

[workspace.dependencies]
forge-core = { path = "crates/forge-core", version = "0.1.0" }
forge-graph = { path = "crates/forge-graph", version = "0.1.0" }
forge-executor = { path = "crates/forge-executor", version = "0.1.0" }
forge-scheduler = { path = "crates/forge-scheduler", version = "0.1.0" }
forge-cache = { path = "crates/forge-cache", version = "0.1.0" }
forge-backend-rust = { path = "crates/forge-backend-rust", version = "0.1.0" }
forge-backend-cc = { path = "crates/forge-backend-cc", version = "0.1.0" }
forge-backend-go = { path = "crates/forge-backend-go", version = "0.1.0" }
forge-backend-ts = { path = "crates/forge-backend-ts", version = "0.1.0" }
forge-backend-py = { path = "crates/forge-backend-py", version = "0.1.0" }
forge-worker = { path = "crates/forge-worker", version = "0.1.0" }
forge-plugin = { path = "crates/forge-plugin", version = "0.1.0" }
forge-remote-cache = { path = "crates/forge-remote-cache", version = "0.1.0" }
forge-sandbox = { path = "crates/forge-sandbox", version = "0.1.0" }

cargo_metadata = "0.21"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"

clap = { version = "4.5", features = ["derive"] }
anstream = "0.6"
anstyle = "1.0"
notify = "6"
crossterm = "0.28"
ratatui = { version = "0.29", default-features = false, features = ["crossterm"] }

tempfile = "3"