[package]
name = "fish-backend-go"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Go build backend for the Fish build system"

[dependencies]
blake3 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
fish-backend-api = { workspace = true }
fish-core = { workspace = true }
fish-executor = { workspace = true }
fish-graph = { workspace = true }
thiserror = { workspace = true }
glob = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
fish-cache = { workspace = true }
fish-scheduler = { workspace = true }
tempfile = { workspace = true }
