use crate::commands::init::DetectedLanguage;

/// Project archetype recognized from the description.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Archetype {
    Cli,
    Api,
    Library,
    Worker,
    Generic,
}

/// A description parsed from plain language.
#[derive(Debug, Clone, PartialEq)]
pub struct ParsedDescription {
    pub languages: Vec<DetectedLanguage>,
    pub archetype: Archetype,
}

fn lang_for(word: &str) -> Option<DetectedLanguage> {
    match word {
        "rust" | "cargo" | "rs" => Some(DetectedLanguage {
            name: "Rust",
            backend: "rust",
            build_cmd: "cargo build",
            test_cmd: "cargo test",
        }),
        "go" | "golang" => Some(DetectedLanguage {
            name: "Go",
            backend: "go",
            build_cmd: "go build ./...",
            test_cmd: "go test ./...",
        }),
        "typescript" | "ts" | "javascript" | "js" | "node" | "npm" => Some(DetectedLanguage {
            name: "TypeScript / Node",
            backend: "ts",
            build_cmd: "npm run build",
            test_cmd: "npm test",
        }),
        "python" | "py" | "pip" | "poetry" => Some(DetectedLanguage {
            name: "Python",
            backend: "python",
            build_cmd: "python -m compileall .",
            test_cmd: "pytest",
        }),
        _ => None,
    }
}

fn archetype_for(words: &[&str]) -> Archetype {
    for w in words {
        match *w {
            "cli" | "binary" | "tool" | "command" => return Archetype::Cli,
            "api" | "server" | "service" | "rest" | "grpc" => return Archetype::Api,
            "lib" | "library" | "crate" | "sdk" => return Archetype::Library,
            "worker" | "queue" | "cron" | "job" => return Archetype::Worker,
            _ => {}
        }
    }
    Archetype::Generic
}

/// Rule-based NL parsing — no LLM dependency.
///
/// Recognizes language keywords (rust, go, ts, python, …) and project
/// archetypes (cli, api, lib, worker). Connectors ("with", "and", "+")
/// are ignored. Duplicate languages collapse to their first mention.
pub fn parse_description(input: &str) -> ParsedDescription {
    let lowered = input.to_lowercase();
    let words: Vec<&str> = lowered
        .split(|c: char| c.is_whitespace() || c == ',' || c == '+')
        .filter(|w| !w.is_empty() && !matches!(*w, "a" | "an" | "and" | "with" | "the" | "for"))
        .collect();

    let mut languages: Vec<DetectedLanguage> = Vec::new();
    for word in &words {
        if let Some(lang) = lang_for(word) {
            if !languages.iter().any(|l| l.backend == lang.backend) {
                languages.push(lang);
            }
        }
    }

    ParsedDescription {
        languages,
        archetype: archetype_for(&words),
    }
}

/// Render a `fish.yaml` body from the parsed description.
///
/// The archetype adds a commented hint so users know what was inferred;
/// task wiring is identical to auto-detection.
pub fn generate_from_description(parsed: &ParsedDescription) -> String {
    let mut out = String::from("# Generated by `fish init --describe`\n");
    out.push_str(&format!("# archetype: {:?}\n", parsed.archetype));
    out.push_str("version: \"1\"\n\ntasks:\n");

    if parsed.languages.is_empty() {
        out.push_str("  build:\n    command: echo \"Building project...\"\n\n");
        out.push_str(
            "  test:\n    command: echo \"Running tests...\"\n    depends_on:\n      - build\n",
        );
        return out;
    }

    for lang in &parsed.languages {
        let prefix = lang.backend;
        out.push_str(&format!("  {prefix}-build:\n"));
        out.push_str(&format!("    command: {}\n", lang.build_cmd));
        out.push_str("    cache:\n      enabled: true\n\n");
        out.push_str(&format!("  {prefix}-test:\n"));
        out.push_str(&format!("    command: {}\n", lang.test_cmd));
        out.push_str(&format!("    depends_on:\n      - {prefix}-build\n\n"));
    }

    out.push_str("  build:\n    depends_on:\n");
    for lang in &parsed.languages {
        out.push_str(&format!("      - {}-build\n", lang.backend));
    }
    out.push_str("\n  test:\n    depends_on:\n");
    for lang in &parsed.languages {
        out.push_str(&format!("      - {}-test\n", lang.backend));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_two_languages() {
        let p = parse_description("rust cli + python tools");
        assert_eq!(p.archetype, Archetype::Cli);
        assert_eq!(p.languages.len(), 2);
        assert_eq!(p.languages[0].backend, "rust");
        assert_eq!(p.languages[1].backend, "python");
    }

    #[test]
    fn recognizes_api_archetype() {
        let p = parse_description("a rust api server with postgres");
        assert_eq!(p.archetype, Archetype::Api);
        assert_eq!(p.languages.len(), 1);
    }

    #[test]
    fn dedupes_repeated_languages() {
        let p = parse_description("rust and cargo and rs");
        assert_eq!(p.languages.len(), 1);
    }

    #[test]
    fn unknown_words_yield_generic_empty() {
        let p = parse_description("something something postgres");
        assert!(p.languages.is_empty());
        assert_eq!(p.archetype, Archetype::Generic);
    }

    #[test]
    fn output_is_valid_yaml_shape() {
        let p = parse_description("go worker + ts frontend");
        let yaml = generate_from_description(&p);
        assert!(yaml.contains("go-build:"));
        assert!(yaml.contains("ts-test:"));
        assert!(yaml.contains("- go-build"));
        assert!(yaml.starts_with("# Generated by"));
    }

    #[test]
    fn empty_description_falls_back_to_echo() {
        let yaml = generate_from_description(&parse_description(""));
        assert!(yaml.contains("echo \"Building project...\""));
    }
}
