#![forbid(unsafe_code)]

//! `fish __gen-docs`: regenerate `docs/cli-reference.md` from the clap
//! definitions themselves.
//!
//! Single source of truth: the reference can never drift from the real
//! parser because it IS the parser. CI re-runs this and fails on any
//! diff, so a new flag without docs is a broken build.

use std::path::PathBuf;
use std::process::ExitCode;

use clap::{Command, CommandFactory};

const BANNER: &str = "<!-- AUTO-GENERATED by `fish __gen-docs` — do not edit by hand.\n\
                      Regenerate with: cargo run -p fish-cli -- __gen-docs -->\n";

pub fn run_gen_docs(path: Option<PathBuf>) -> ExitCode {
    let mut root = crate::args::Cli::command();
    root.build();

    let mut out = String::with_capacity(64 * 1024);
    out.push_str(BANNER);
    out.push_str("# Fish CLI Reference\n\n");

    emit_command(&mut root, 2, &mut out);

    let target = path.unwrap_or_else(|| PathBuf::from("docs/cli-reference.md"));
    if let Some(parent) = target.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    match std::fs::write(&target, out) {
        Ok(()) => {
            println!("[ok] wrote {}", target.display());
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("error: failed to write {}: {e}", target.display());
            ExitCode::FAILURE
        }
    }
}

fn slug(name: &str, parents: &[String]) -> String {
    if parents.is_empty() {
        name.to_string()
    } else {
        format!("{}-{name}", parents.join("-"))
    }
}

fn emit_command(cmd: &mut Command, level: usize, out: &mut String) {
    let name = cmd.get_name().to_string();
    // Thread of parent names gives stable anchors like `fish-cache-server`.
    thread_local! {
        static TRAIL: std::cell::RefCell<Vec<String>> = const { std::cell::RefCell::new(Vec::new()) };
    }
    let anchor = TRAIL.with(|t| {
        let parents = t.borrow().clone();
        let s = slug(&name, &parents);
        t.borrow_mut().push(name.clone());
        s
    });

    let hashes = "#".repeat(level);
    out.push_str(&format!("{hashes} {anchor}\n\n"));

    if let Some(about) = cmd.get_about() {
        out.push_str(&format!("{about}\n\n"));
    }

    // Usage line straight from clap so it always matches reality.
    out.push_str(&format!("```\n{}\n```\n\n", cmd.render_usage()));

    // Arguments table. Globals (like --experimental) propagate to
    // every node, so list them once at the root to avoid noise.
    let rows: Vec<Vec<String>> = cmd
        .get_arguments()
        .filter(|a| {
            !a.is_hide_set()
                && a.get_id() != "help"
                && a.get_id() != "version"
                && (level == 2 || !a.is_global_set())
        })
        .map(|a| {
            let flags = match (a.get_long(), a.get_short()) {
                (Some(l), Some(s)) => format!("`--{l}`, `-{s}`"),
                (Some(l), None) => format!("`--{l}`"),
                (None, Some(s)) => format!("`-{s}`"),
                (None, None) => a.get_id().to_string(),
            };
            let value = if a.get_num_args().map(|n| n.takes_values()).unwrap_or(false) {
                let vn = a
                    .get_value_names()
                    .and_then(|names| names.first())
                    .map(|v| v.to_string())
                    .unwrap_or_else(|| "value".into());
                format!(" `<{vn}>`")
            } else {
                String::new()
            };
            let default = a
                .get_default_values()
                .iter()
                .map(|v| v.to_string_lossy().to_string())
                .collect::<Vec<_>>()
                .join(", ");
            vec![
                format!("{flags}{value}"),
                a.get_help()
                    .map(|h| h.to_string())
                    .unwrap_or_default()
                    .replace('|', "\\|"),
                if default.is_empty() {
                    String::new()
                } else {
                    format!("`{default}`")
                },
            ]
        })
        .collect();

    if !rows.is_empty() {
        out.push_str("| Flag | Description | Default |\n|---|---|---|\n");
        for row in rows {
            out.push_str(&format!("| {} | {} | {} |\n", row[0], row[1], row[2]));
        }
        out.push('\n');
    }

    // Subcommand index for this node.
    let subs: Vec<String> = cmd
        .get_subcommands()
        .filter(|s| !s.is_hide_set() && s.get_name() != "help")
        .map(|s| s.get_name().to_string())
        .collect();
    if !subs.is_empty() {
        out.push_str("**Subcommands:** ");
        out.push_str(
            &subs
                .iter()
                .map(|s| format!("[`{s}`](#{anchor}-{s})"))
                .collect::<Vec<_>>()
                .join(", "),
        );
        out.push_str("\n\n");
    }

    for sub in cmd.get_subcommands_mut() {
        if sub.is_hide_set() {
            continue;
        }
        emit_command(sub, level + 1, out);
    }

    TRAIL.with(|t| {
        t.borrow_mut().pop();
    });
}
