[package]
name = "fish-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Fish core library: project discovery and Cargo metadata integration"

[dependencies]
anyhow = { workspace = true }
cargo_metadata = { workspace = true }
fish-graph = { workspace = true }
thiserror = { workspace = true }
spin = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
blake3 = { workspace = true }
uuid = { workspace = true }
glob = { workspace = true }
walkdir = { workspace = true }
tempfile = { workspace = true }
sha2 = { workspace = true }
flate2 = "1.0"
banana = { workspace = true }
tar = { workspace = true }
zip = { version = "2", default-features = false, features = ["deflate"] }
ureq = { version = "2", default-features = false, features = ["tls"] }

[dev-dependencies]