[build]
incremental = true

[resolver]
incompatible-rust-versions = "fallback"

[target.'cfg(target_os = "windows")']
rustflags = [
    "-C", "link-arg=/OPT:REF",
    "-C", "link-arg=/OPT:ICF",
]

[target.'cfg(target_os = "linux")']
rustflags = [
    "-C", "link-arg=-Wl,--gc-sections",
]

[target.'cfg(target_os = "macos")']
rustflags = [
    "-C", "link-arg=-Wl,-dead_strip",
]
