#![forbid(unsafe_code)]

use crate::matrix::CIMatrix;
use crate::{CIConfig, CIGeneratorError, Result};
use handlebars::Handlebars;
use serde_json::json;

pub struct AzurePipelinesGenerator {
    config: CIConfig,
}

impl AzurePipelinesGenerator {
    pub fn new(config: CIConfig) -> Self {
        Self { config }
    }

    pub fn generate(&self, matrix: &CIMatrix) -> Result<String> {
        let mut handlebars = Handlebars::new();

        let template = r#"trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - main
      - develop

variables:
  FISH_CACHE_ENABLED: "{{cache_enabled}}"
  {{#if remote_cache_url}}
  FISH_REMOTE_CACHE: "{{remote_cache_url}}"
  {{/if}}

jobs:
  {{#each jobs}}
  - job: {{name}}
    displayName: "Build {{name}}"
    pool:
      vmImage: "ubuntu-latest"
    timeoutInMinutes: {{timeout_minutes}}
    {{#if dependencies}}
    dependsOn:
      {{#each dependencies}}
      - {{this}}
      {{/each}}
    {{/if}}
    steps:
      - checkout: self
      - script: |
          curl -L https://github.com/your-org/forge/releases/latest/download/fish-linux -o forge
          chmod +x forge
          sudo mv forge /usr/local/bin/
        displayName: "Install Fish"
      {{#if cache_enabled}}
      - task: Cache@2
        inputs:
          key: 'fish-cache | "$(Agent.OS)" | {{id}}'
          path: $(HOME)/.forge/cache
        displayName: "Cache Fish artifacts"
      {{/if}}
      - script: |
          {{#each commands}}
          {{this}}
          {{/each}}
        displayName: "Run Fish tasks"
  {{/each}}
"#;

        handlebars.register_template_string("azure_pipelines", template)?;

        let data = json!({
            "cache_enabled": matrix.cache_config.enabled,
            "remote_cache_url": matrix.cache_config.remote_url,
            "timeout_minutes": self.config.timeout_minutes,
            "jobs": matrix.jobs.iter().map(|job| {
                json!({
                    "name": job.id.replace('-', "_"),
                    "id": job.id,
                    "backend": job.backend,
                    "commands": job.commands,
                    "artifacts": job.artifacts,
                    "dependencies": job.dependencies.iter().map(|d| d.replace('-', "_")).collect::<Vec<_>>(),
                    "cache_enabled": matrix.cache_config.enabled,
                    "timeout_minutes": self.config.timeout_minutes,
                })
            }).collect::<Vec<_>>(),
        });

        handlebars
            .render("azure_pipelines", &data)
            .map_err(|e| CIGeneratorError::TemplateError(e.to_string()))
    }

    pub fn generate_pipeline(&self, matrix: &CIMatrix) -> Result<String> {
        let content = self.generate(matrix)?;
        Ok(format!(
            r#"# Auto-generated by forge ci init
# Azure DevOps Pipeline

{}
"#,
            content
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::CIJob;

    #[test]
    fn test_azure_pipelines_generation() {
        let config = CIConfig::default();
        let generator = AzurePipelinesGenerator::new(config);

        let mut matrix = CIMatrix::new();
        matrix.add_job(CIJob {
            id: "test-job".to_string(),
            name: "Test Job".to_string(),
            backend: "rust".to_string(),
            commands: vec!["forge build".to_string()],
            artifacts: vec![],
            dependencies: vec![],
            cache_key: "test-key".to_string(),
        });

        let result = generator.generate_pipeline(&matrix);
        assert!(result.is_ok());
        let output = result.unwrap();
        assert!(output.contains("vmImage: \"ubuntu-latest\""));
        assert!(output.contains("test_job"));
    }
}
