#![forbid(unsafe_code)]

use crate::matrix::CIMatrix;
use crate::{CIConfig, CIGeneratorError, Result};
use handlebars::Handlebars;
use serde_json::json;

pub struct CircleCIGenerator {
    config: CIConfig,
}

impl CircleCIGenerator {
    pub fn new(config: CIConfig) -> Self {
        Self { config }
    }

    pub fn generate(&self, matrix: &CIMatrix) -> Result<String> {
        let mut handlebars = Handlebars::new();

        let template = r#"version: 2.1

executors:
  fish-executor:
    docker:
      - image: cimg/rust:1.80
    resource_class: medium
    working_directory: ~/project

parameters:
  cache_enabled:
    type: boolean
    default: true
  remote_cache_url:
    type: string
    default: ""

{{#each jobs}}
{{name}}:
  executor: fish-executor
  {{#if dependencies}}
  requires:
    {{#each dependencies}}
    - {{this}}
    {{/each}}
  {{/if}}
  steps:
    - checkout
    - setup:
        name: Setup Fish
        command: |
          curl -L https://github.com/requla11/fish/releases/latest/download/fish-linux -o fish
          chmod +x fish
          sudo mv fish /usr/local/bin/
    {{#if cache_enabled}}
    - restore_cache:
        name: Restore Fish Cache
        keys:
          - fish-cache-{{id}}
          - fish-cache-
        paths:
          - ~/.fish/cache
    {{/if}}
    - build:
        name: Build {{name}}
        command: |
          {{#each commands}}
          {{this}}
          {{/each}}
    {{#if cache_enabled}}
    - save_cache:
        name: Save Fish Cache
        key: fish-cache-{{id}}
        paths:
          - ~/.fish/cache
        when: always
    {{/if}}
    {{#if artifacts}}
    - store_artifacts:
        path: |
          {{#each artifacts}}
          {{this}}
          {{/each}}
    {{/if}}
{{/each}}
"#;

        handlebars.register_template_string("circleci", template)?;

        let data = json!({
            "cache_enabled": matrix.cache_config.enabled,
            "remote_cache_url": matrix.cache_config.remote_url,
            "timeout_minutes": self.config.timeout_minutes,
            "jobs": matrix.jobs.iter().map(|job| {
                json!({
                    "name": job.id,
                    "id": job.id,
                    "backend": job.backend,
                    "commands": job.commands,
                    "artifacts": job.artifacts,
                    "dependencies": job.dependencies,
                    "cache_key": job.cache_key,
                    "cache_enabled": matrix.cache_config.enabled,
                })
            }).collect::<Vec<_>>(),
        });

        handlebars
            .render("circleci", &data)
            .map_err(|e| CIGeneratorError::TemplateError(e.to_string()))
    }

    pub fn generate_config(&self, matrix: &CIMatrix) -> Result<String> {
        let content = self.generate(matrix)?;

        Ok(format!(
            r#"# Auto-generated by fish ci init
#
# This config is optimized based on your build graph:
# - Parallel execution where possible
# - Cache configuration enabled
# - Artifact sharing between jobs
# - Remote cache support if configured

{}
"#,
            content
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::CIJob;

    #[test]
    fn test_circleci_generation() {
        let config = CIConfig::default();
        let generator = CircleCIGenerator::new(config);

        let mut matrix = CIMatrix::new();
        matrix.add_job(CIJob {
            id: "test-job".to_string(),
            name: "Test Job".to_string(),
            backend: "rust".to_string(),
            commands: vec!["cargo build".to_string()],
            artifacts: vec![],
            dependencies: vec![],
            cache_key: "test-key".to_string(),
        });

        let result = generator.generate(&matrix);
        if let Err(e) = &result {
            println!("CircleCI generation error: {}", e);
        }
        assert!(result.is_ok());
    }
}
