#![forbid(unsafe_code)]

use crate::matrix::CIMatrix;
use crate::{CIConfig, CIGeneratorError, Result};
use handlebars::Handlebars;
use serde_json::json;

pub struct BitbucketPipelineGenerator {
    config: CIConfig,
}

impl BitbucketPipelineGenerator {
    pub fn new(config: CIConfig) -> Self {
        Self { config }
    }

    pub fn generate(&self, matrix: &CIMatrix) -> Result<String> {
        let mut handlebars = Handlebars::new();

        let template = r#"image: atlassian/default-image:4

definitions:
  caches:
    forge-cache: ~/.forge/cache
  steps:
    - step: &setup-forge
        name: Setup Forge
        script:
          - curl -L https://github.com/your-org/forge/releases/latest/download/forge-linux -o forge
          - chmod +x forge
          - sudo mv forge /usr/local/bin/
    - step: &cache-restore
        name: Restore Forge Cache
        cache:
          - forge-cache
        script:
          - echo "Cache restored"
    - step: &cache-save
        name: Save Forge Cache
        cache:
          - forge-cache
        script:
          - echo "Cache saved"

pipelines:
  default:
    {{#each jobs}}
    - parallel:
        {{name}}:
          <<: *setup-forge
          {{#if cache_enabled}}
          <<: *cache-restore
          {{/if}}
          step:
            name: Build {{name}}
            script:
              {{#each commands}}
              - {{this}}
              {{/each}}
          {{#if cache_enabled}}
          <<: *cache-save
          {{/if}}
          {{#if artifacts}}
          artifacts:
            {{#each artifacts}}
            - {{this}}
            {{/each}}
          {{/if}}
    {{/each}}

{{#each jobs}}
{{name}}:
  - step:
      name: Build {{name}}
      script:
        {{#each commands}}
        - {{this}}
        {{/each}}
      {{#if cache_enabled}}
      caches:
        - forge-cache
      {{/if}}
      {{#if artifacts}}
      artifacts:
        {{#each artifacts}}
        - {{this}}
        {{/each}}
      {{/if}}
{{/each}}
"#;

        handlebars.register_template_string("bitbucket", template)?;

        let data = json!({
            "cache_enabled": matrix.cache_config.enabled,
            "remote_cache_url": matrix.cache_config.remote_url,
            "timeout_minutes": self.config.timeout_minutes,
            "jobs": matrix.jobs.iter().map(|job| {
                json!({
                    "name": job.id,
                    "id": job.id,
                    "backend": job.backend,
                    "commands": job.commands,
                    "artifacts": job.artifacts,
                    "dependencies": job.dependencies,
                    "cache_key": job.cache_key,
                    "cache_enabled": matrix.cache_config.enabled,
                })
            }).collect::<Vec<_>>(),
        });

        handlebars
            .render("bitbucket", &data)
            .map_err(|e| CIGeneratorError::TemplateError(e.to_string()))
    }

    pub fn generate_config(&self, matrix: &CIMatrix) -> Result<String> {
        let content = self.generate(matrix)?;

        Ok(format!(
            r#"# Auto-generated by forge ci init
#
# This pipeline is optimized based on your build graph:
# - Parallel execution where possible
# - Cache configuration enabled
# - Artifact sharing between jobs
# - Remote cache support if configured

{}
"#,
            content
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::CIJob;

    #[test]
    fn test_bitbucket_generation() {
        let config = CIConfig::default();
        let generator = BitbucketPipelineGenerator::new(config);

        let mut matrix = CIMatrix::new();
        matrix.add_job(CIJob {
            id: "test-job".to_string(),
            name: "Test Job".to_string(),
            backend: "rust".to_string(),
            commands: vec!["cargo build".to_string()],
            artifacts: vec![],
            dependencies: vec![],
            cache_key: "test-key".to_string(),
        });

        let result = generator.generate(&matrix);
        assert!(result.is_ok());
    }
}
