#![forbid(unsafe_code)]

use crate::matrix::CIMatrix;
use crate::{CIGeneratorError, CIConfig, Result};
use handlebars::Handlebars;
use serde_json::json;

pub struct GitHubActionsGenerator {
    config: CIConfig,
}

impl GitHubActionsGenerator {
    pub fn new(config: CIConfig) -> Self {
        Self { config }
    }
    
    pub fn generate(&self, matrix: &CIMatrix) -> Result<String> {
        let mut handlebars = Handlebars::new();
        
        let template = r#"name: Forge CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  FORGE_CACHE_ENABLED: "{{cache_enabled}}"
  {{#if remote_cache_url}}
  FORGE_REMOTE_CACHE: "{{remote_cache_url}}"
  {{/if}}

jobs:
  {{#each jobs}}
  {{name}}:
    runs-on: ubuntu-latest
    timeout-minutes: "30"
    {{#if dependencies}}
    needs: [{{#each dependencies}}"{{this}}"{{#unless @last}}, {{/unless}}{{/each}}]
    {{/if}}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Forge
        run: |
          curl -L https://github.com/your-org/forge/releases/latest/download/forge-linux -o forge
          chmod +x forge
          sudo mv forge /usr/local/bin/
      
      {{#if cache_enabled}}
      - name: Cache Forge artifacts
        uses: actions/cache@v4
        with:
          path: ~/.forge/cache
          key: forge-cache-{{id}}
          restore-keys: forge-cache-
      {{/if}}
      
      - name: Build {{name}}
        run: |
          {{#each commands}}
          {{this}}
          {{/each}}
      
      {{#if artifacts}}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: {{name}}-artifacts
          path: |
            {{#each artifacts}}
            {{this}}
            {{/each}}
      {{/if}}
  {{/each}}
"#;
        
        handlebars.register_template_string("github_actions", template)?;
        
        let data = json!({
            "cache_enabled": matrix.cache_config.enabled,
            "remote_cache_url": matrix.cache_config.remote_url,
            "timeout_minutes": self.config.timeout_minutes,
            "jobs": matrix.jobs.iter().map(|job| {
                json!({
                    "name": job.id,
                    "id": job.id,
                    "backend": job.backend,
                    "commands": job.commands,
                    "artifacts": job.artifacts,
                    "dependencies": job.dependencies,
                    "cache_enabled": matrix.cache_config.enabled,
                    "timeout_minutes": self.config.timeout_minutes,
                })
            }).collect::<Vec<_>>(),
        });
        
        handlebars.render("github_actions", &data)
            .map_err(|e| CIGeneratorError::TemplateError(e.to_string()))
    }
    
    pub fn generate_workflow(&self, matrix: &CIMatrix) -> Result<String> {
        let content = self.generate(matrix)?;
        
        Ok(format!(
            r#"# Auto-generated by forge ci init
# 
# This workflow is optimized based on your build graph:
# - Parallel execution where possible
# - Cache configuration enabled
# - Artifact sharing between jobs
# - Remote cache support if configured

{}
"#,
            content
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::CIJob;
    
    #[test]
    fn test_github_actions_generation() {
        let config = CIConfig::default();
        let generator = GitHubActionsGenerator::new(config);
        
        let mut matrix = CIMatrix::new();
        matrix.add_job(CIJob {
            id: "test-job".to_string(),
            name: "Test Job".to_string(),
            backend: "rust".to_string(),
            commands: vec!["cargo build".to_string()],
            artifacts: vec![],
            dependencies: vec![],
            cache_key: "test-key".to_string(),
        });
        
        let result = generator.generate(&matrix);
        assert!(result.is_ok());
    }
}
