#![forbid(unsafe_code)]

use crate::matrix::CIMatrix;
use crate::{CIGeneratorError, CIConfig, Result};
use handlebars::Handlebars;
use serde_json::json;

pub struct GitLabCIGenerator {
    config: CIConfig,
}

impl GitLabCIGenerator {
    pub fn new(config: CIConfig) -> Self {
        Self { config }
    }
    
    pub fn generate(&self, matrix: &CIMatrix) -> Result<String> {
        let mut handlebars = Handlebars::new();
        
        let template = r#"stages:
  {{#each stages}}
  - {{this}}
  {{/each}}

variables:
  FORGE_CACHE_ENABLED: "{{cache_enabled}}"
  {{#if remote_cache_url}}
  FORGE_REMOTE_CACHE: "{{remote_cache_url}}"
  {{/if}}

{{#each jobs}}
{{name}}:
  stage: {{stage}}
  timeout: "30" minutes
  {{#if dependencies}}
  needs:
    {{#each dependencies}}
    - {{this}}
    {{/each}}
  {{/if}}
  script:
    {{#each commands}}
    - {{this}}
    {{/each}}
  {{#if cache_enabled}}
  cache:
    key: "$CI_COMMIT_REF_SLUG-{{id}}"
    paths:
      - .forge/cache
  {{/if}}
  {{#if artifacts}}
  artifacts:
    paths:
      {{#each artifacts}}
      - {{this}}
      {{/each}}
  {{/if}}
{{/each}}
"#;
        
        handlebars.register_template_string("gitlab_ci", template)?;
        
        let parallel_levels = matrix.get_parallel_levels();
        let stages: Vec<String> = parallel_levels.iter().enumerate().map(|(i, _)| format!("stage-{}", i)).collect();
        
        let data = json!({
            "cache_enabled": matrix.cache_config.enabled,
            "remote_cache_url": matrix.cache_config.remote_url,
            "timeout_minutes": self.config.timeout_minutes,
            "stages": stages,
            "jobs": matrix.jobs.iter().map(|job| {
                // Determine stage based on parallel level
                let stage = parallel_levels.iter()
                    .position(|level| level.iter().any(|id| id == &job.id))
                    .map(|level| format!("stage-{}", level))
                    .unwrap_or_else(|| "build".to_string());
                
                json!({
                    "name": job.id,
                    "id": job.id,
                    "backend": job.backend,
                    "commands": job.commands,
                    "artifacts": job.artifacts,
                    "dependencies": job.dependencies,
                    "cache_key": job.cache_key,
                    "stage": stage,
                    "cache_enabled": matrix.cache_config.enabled,
                })
            }).collect::<Vec<_>>(),
        });
        
        handlebars.render("gitlab_ci", &data)
            .map_err(|e| CIGeneratorError::TemplateError(e.to_string()))
    }
    
    pub fn generate_pipeline(&self, matrix: &CIMatrix) -> Result<String> {
        let content = self.generate(matrix)?;
        
        Ok(format!(
            r#"# Auto-generated by forge ci init
# 
# This pipeline is optimized based on your build graph:
# - Parallel execution where possible
# - Cache configuration enabled
# - Artifact sharing between jobs
# - Remote cache support if configured

{}
"#,
            content
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::CIJob;
    
    #[test]
    fn test_gitlab_ci_generation() {
        let config = CIConfig::default();
        let generator = GitLabCIGenerator::new(config);
        
        let mut matrix = CIMatrix::new();
        matrix.add_job(CIJob {
            id: "test-job".to_string(),
            name: "Test Job".to_string(),
            backend: "rust".to_string(),
            commands: vec!["cargo build".to_string()],
            artifacts: vec![],
            dependencies: vec![],
            cache_key: "test-key".to_string(),
        });
        
        let result = generator.generate(&matrix);
        assert!(result.is_ok());
    }
}
