[package]
name = "fish-plugin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Custom build rules and plugin engine for Fish"

[dependencies]
blake3 = "1"
serde = { version = "1", features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
ureq = { version = "2", default-features = false, features = ["tls"] }
base64 = { workspace = true }
ed25519-dalek = { workspace = true }
fish-core = { workspace = true }
fish-executor = { workspace = true }
fish-graph = { workspace = true }
thiserror = { workspace = true }
wasmi = { version = "0.31", optional = true }

[features]
default = ["wasm"]
wasm = ["dep:wasmi"]

[dev-dependencies]
fish-cache = { workspace = true }
fish-scheduler = { workspace = true }
tempfile = { workspace = true }
