[package]
name = "forge-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Forge command-line interface"

[[bin]]
name = "forge"
path = "src/main.rs"

[dependencies]
forge-core = { workspace = true }
forge-graph = { workspace = true }
forge-executor = { workspace = true }
forge-scheduler = { workspace = true }
forge-cache = { workspace = true }
forge-backend-rust = { workspace = true }
cargo_metadata = { workspace = true }

clap = { workspace = true }
anstream = { workspace = true }
anstyle = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }